baseurl: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-menus
  - liquid-md5
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - faviconData.json
  - package.json
  - package-lock.json
  - README.md
  - '*.orig'
  - '*.log'

include:
  - .nojekyll

permalink: /blog/:categories/:title/
categories: [ hire, graduate, landing ]
