version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-
            - v1-gem-cache-{{ arch }}-
      - run: bundle install --path ~/.bundle && bundle clean
      - save_cache:
          paths:
            - ~/.bundle
          key: v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn test
      - run: mkdir _data
      - run: node _javascripts/events.js
      - run: node _javascripts/tutoring.js
      - run: deploy.sh
      - deploy:
          name: Deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "preview" ]; then
                git config --global user.email "kevin@austincodingacademy.com"
                git config --global user.name "Kevin Colten"
                yarn images
                KEY=austincodingacademy.com yarn favicon
                KEY=austincodingacademy.com yarn build
                yarn optimize
                # yarn encrypt
                KEY=austincodingacademy.com PREVIEW='preview.' yarn deploy
                KEY=lubbockcodingacademy.com yarn favicon
                KEY=lubbockcodingacademy.com yarn build
                yarn optimize
                # yarn encrypt
                KEY=lubbockcodingacademy.com PREVIEW='preview.' yarn deploy
                KEY=texastechcodingacademy.com yarn favicon
                KEY=texastechcodingacademy.com yarn build
                yarn optimize
                # yarn encrypt
                KEY=texastechcodingacademy.com PREVIEW='preview.' yarn deploy
              fi
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                git config --global user.email "kevin@austincodingacademy.com"
                git config --global user.name "Kevin Colten"
                yarn images
                KEY=austincodingacademy.com yarn sitemap
                KEY=austincodingacademy.com yarn favicon
                KEY=austincodingacademy.com yarn build
                yarn optimize
                sudo apt install rsync
                rsync -a --delete -e "ssh -o StrictHostKeyChecking=no" _site/ root@134.209.57.190:/usr/share/nginx/html
                KEY=lubbockcodingacademy.com yarn sitemap
                KEY=lubbockcodingacademy.com yarn favicon
                KEY=lubbockcodingacademy.com yarn build
                yarn optimize
                KEY=lubbockcodingacademy.com yarn deploy
                KEY=texastechcodingacademy.com yarn sitemap
                KEY=texastechcodingacademy.com yarn favicon
                KEY=texastechcodingacademy.com yarn build
                yarn optimize
                KEY=texastechcodingacademy.com yarn deploy
              fi

workflows:
  version: 2
  commit:
    jobs:
      - build:
        filters:
          branches:
            ignore: gh-pages
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
