---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets/uploads
public_path: "/assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: yarn && bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6-node10
  mount_path: "/srv"
  instant_preview_command: node _javascripts/postcss.js && cat assets/css/main.min.css
    > _includes/css.html && bundle exec jekyll serve --drafts --unpublished --future
    -d _site --config _config.yml,_configs/austincodingacademy.com.yml --port 8080
    --host 0.0.0.0
