---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
    --config _configs/default.yml
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  - RUBY_VERSION=2.6.2
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: touch _includes/css.html && yarn css && bundle exec jekyll
    serve --config _config.yml --host 0.0.0.0 --port 8080
