---
label: Settings
hide_body: true
fields:
- type: boolean
  name: settings
  label: settings
- type: text
  name: form_url
  label: form_url
- type: number
  name: hubspot_portal_id
  label: hubspot_portal_id
- type: text
  name: instructor_form_guid
  label: instructor_form_guid
- type: text
  name: corporate_trainings_form_guid
  label: corporate_trainings_form_guid
- type: text
  name: corporate_form_guid
  label: corporate_form_guid
- type: text
  name: assignment_form_guid
  label: assignment_form_guid
- type: field_group
  name: austincodingacademy
  label: austincodingacademy
  fields:
  - type: text
    name: school
    label: school
  - type: text
    name: city
    label: city
  - type: text
    name: url
    label: url
  - type: number
    name: phone
    label: phone
  - type: number
    name: callrail_company_id
    label: callrail_company_id
  - type: text
    name: title
    label: title
  - type: textarea
    name: description
    label: description
  - type: text
    name: google_tag_manager
    label: google_tag_manager
  - type: text
    name: google_tag_manager_amp
    label: google_tag_manager_amp
  - type: text
    name: contact_form_guid
    label: contact_form_guid
  - type: text
    name: cta_form_guid
    label: cta_form_guid
  - type: text
    name: course_guide_form_guid
    label: course_guide_form_guid
  - type: text
    name: application_form_guid
    label: application_form_guid
  - type: text
    name: twitter
    label: twitter
  - type: text
    name: eventbrite
    label: eventbrite
  - type: field_group_list
    name: locations
    label: locations
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: street
      label: street
    - type: text
      name: locality
      label: locality
    - type: textarea
      name: url
      label: url
- type: field_group
  name: lubbockcodingacademy
  label: lubbockcodingacademy
  fields:
  - type: text
    name: school
    label: school
  - type: text
    name: city
    label: city
  - type: text
    name: url
    label: url
  - type: number
    name: phone
    label: phone
  - type: number
    name: callrail_company_id
    label: callrail_company_id
  - type: text
    name: title
    label: title
  - type: textarea
    name: description
    label: description
  - type: text
    name: google_tag_manager
    label: google_tag_manager
  - type: text
    name: google_tag_manager_amp
    label: google_tag_manager_amp
  - type: text
    name: contact_form_guid
    label: contact_form_guid
  - type: text
    name: application_form_guid
    label: application_form_guid
  - type: text
    name: course_guide_form_guid
    label: course_guide_form_guid
  - type: text
    name: cta_form_guid
    label: cta_form_guid
  - type: text
    name: twitter
    label: twitter
  - type: field_group_list
    name: locations
    label: locations
    fields:
    - type: text
      name: address
      label: address
    - type: text
      name: street
      label: street
    - type: text
      name: locality
      label: locality
    - type: textarea
      name: url
      label: url
- type: field_group
  name: texastechuniversitycodingacademy
  label: texastechuniversitycodingacademy
  fields:
  - type: text
    name: school
    label: school
  - type: text
    name: city
    label: city
  - type: text
    name: url
    label: url
  - type: text
    name: phone
    label: phone
  - type: text
    name: callrail_company_id
    label: callrail_company_id
  - type: text
    name: title
    label: title
  - type: textarea
    name: description
    label: description
  - type: text
    name: google_tag_manager
    label: google_tag_manager
  - type: text
    name: google_tag_manager_amp
    label: google_tag_manager_amp
  - type: text
    name: contact_form_guid
    label: contact_form_guid
  - type: text
    name: application_form_guid
    label: application_form_guid
  - type: text
    name: course_guide_form_guid
    label: course_guide_form_guid
  - type: text
    name: corporate_form_guid
    label: corporate_form_guid
  - type: text
    name: corporate_trainings_form_guid
    label: corporate_trainings_form_guid
  - type: text
    name: cta_form_guid
    label: cta_form_guid
  - type: text
    name: twitter
    label: twitter
  - type: field_group_list
    name: locations
    label: locations
    fields:
    - type: text
      name: address
      label: address
    - type: text
      name: street
      label: street
    - type: text
      name: locality
      label: locality
    - type: text
      name: url
      label: url
pages:
- settings.html
